---
- name: Wait for apt lock
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done

- name: Install apt-transport-https package
  become: true
  apt:
    name: apt-transport-https
    state: present
  when: lynis_configure_repository|bool
  changed_when: false

- name: Add repository gpg key
  become: true
  apt_key:
    url: "{{ lynis_debian_repository_key }}"
  when: lynis_configure_repository|bool

- name: Add repository
  become: true
  apt_repository:
    repo: "{{ lynis_debian_repository }}"
    state: present
    filename: lynis
    update_cache: true
    mode: 0600
  when: lynis_configure_repository|bool

- name: Wait for apt lock
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done

- name: Install lynis package
  become: true
  apt:
    name: "{{ lynis_package_name }}"
    state: present
