---
- name: Check minimum number of name servers
  fail:
    msg: |
      {{ resolvconf_minimum_number_of_nameservers }} or more name servers
      must be configured. Currently only {{ resolvconf_nameserver|length }}
      name server(s) are configured.
  when: resolvconf_nameserver|length < resolvconf_minimum_number_of_nameservers|int

- name: Include release specific tasks
  include: "{{ ansible_distribution_release }}.yml"
  when: resolvconf_nameserver|length > 0
