---
- name: Install required packages
  become: true
  package:
    name: "{{ resolvconf_package }}"
    state: present
  when: resolvconf_package|length

- name: Copy configuration files
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - src: xenial/head.j2
      dest: /etc/resolvconf/resolv.conf.d/head

- name: Start/enable resolvconf service
  become: true
  service:
    name: resolvconf
    state: started
    enabled: yes
  ignore_errors: true

- name: Update resolvconf file
  become: true
  command: resolvconf -u
  changed_when: false
