---
namespace: osism
name: commons
version: 0.1.0
readme: README.md
authors:
  - OSISM community <info@osism.de> (https://github.com/osism/ansible-collection-commons/graphs/contributors)
description: OSISM common roles
license_file: LICENSE
tags:
  - system
dependencies: {}
repository: https://github.com/osism/ansible-collection-commons.git
documentation: https://docs.osism.de
homepage: https://osism.de
issues: https://github.com/osism/ansible-collection-commons/issues
