---
- name: Create host groups
  local_action:
    module: community.zabbix.zabbix_group
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_username }}"
    login_password: "{{ zabbix_login_password }}"
    state: present
    host_groups: "{{ item }}"
  # NOTE: At this point was intentionally used a loop
  loop: "{{ zabbix_host_groups }}"

- name: Create templates
  ignore_errors: true
  local_action:
    module: community.zabbix.zabbix_template
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_username }}"
    login_password: "{{ zabbix_login_password }}"
    state: present
    # NOTE: zabbix_template can only import XML or JSON, but in YAML
    #       the templates read much better
    template_json: "{{ lookup('file', item ) | from_yaml | to_json }}"
  loop: "{{ zabbix_templates }}"
