---
- name: Gather variables for each operating system
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include distribution specific package tasks
  include_tasks: "package-{{ ansible_os_family }}.yml"
