---
- name: Update package cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Upgrade packages
  become: true
  apt:
    upgrade: dist
  when: upgrade_packages|bool

- name: Install required packages
  become: true
  apt:
    name: "{{ required_packages }}"
    state: present
