---
- name: git - set configuration_git_repositroy_url fact (with username)
  set_fact:
    configuration_git_repository_url: "{{ configuration_git_protocol }}://{{ configuration_git_username }}@{{ configuration_git_host }}:{{ configuration_git_port }}/{{ configuration_git_repository }}"  # noqa 204
  when: configuration_git_username is defined and configuration_git_username|length

- name: git - set configuration_git_repositroy_url fact (without username)
  set_fact:
    configuration_git_repository_url: "{{ configuration_git_protocol }}://{{ configuration_git_host }}:{{ configuration_git_port }}/{{ configuration_git_repository }}"  # noqa 204
  when: configuration_git_username is not defined or not configuration_git_username|length

- name: git - copy private ssh key
  copy:
    content: "{{ configuration_git_private_key }}"
    dest: "{{ configuration_git_private_key_file }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0600
  when: (configuration_git_protocol == 'ssh' and configuration_git_private_key is defined and configuration_git_private_key|length)
  no_log: true

- name: git - install required packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git

- name: git - clone configuration repository (ssh / with auth)
  git:
    repo: "{{ configuration_git_repository_url }}"
    dest: "{{ configuration_directory }}"
    version: "{{ configuration_git_version }}"
    key_file: "{{ configuration_git_private_key_file }}"
    accept_hostkey: yes
    force: yes
  when: configuration_git_protocol == 'ssh'

- name: git - clone configuration repository (without auth)
  git:
    repo: "{{ configuration_git_repository_url }}"
    dest: "{{ configuration_directory }}"
    version: "{{ configuration_git_version }}"
    accept_hostkey: yes
    force: yes
  when: (configuration_git_protocol == 'ssh' and (configuration_git_private_key is not defined or not configuration_git_private_key|length)) or
        configuration_git_protocol != 'ssh'
