---
- name: Update package cache
  become: true
  apt:
    update_cache: yes

- name: Install required packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - gpg

# NOTE: this directory does not exist inside a Docker image

- name: Create /etc/modules-load.d directory
  become: true
  file:
    path: /etc/modules-load.d
    state: directory
    owner: root
    group: root
    mode: 0775
