---
- name: Collect facts about services
  scan_services:

- name: Cleanup services
  become: true
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  ignore_errors: true
  loop: "{{ cleanup_services }}"
  when: item + ".service" in services
