---
- name: Install rng package
  apt:
    name: "{{ rng_package_name }}"
    state: present
  become: true

- name: Start/enable rng service
  service:
    name: "{{ rng_service_name }}"
    state: started
    enabled: yes
  become: true
