---
zabbix_server_host: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
zabbix_server_port: 8160
zabbix_server_url: "http://{{ zabbix_server_host }}:{{ zabbix_server_port }}"

zabbix_login_username: Admin
zabbix_login_password: zabbix

zabbix_host_groups_default:
  - ceph-control
  - ceph-resource
  - compute
  - control
  - generic
  - linux
  - manager
  - monitoring
  - network
zabbix_host_groups_extra: []
zabbix_host_groups: "{{ zabbix_host_groups_default + zabbix_host_groups_extra }}"

zabbix_templates_default:
  - template-glance.yaml
zabbix_templates_extra: []
zabbix_templates: "{{ zabbix_templates_default + zabbix_templates_extra }}"
