---
- name: Collect facts about services
  scan_services:

- name: Include distribution specific configure tasks
  include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: Copy motd file
  become: true
  copy:
    content: "{{ motd_content }}"
    dest: "{{ motd_path }}"
    owner: root
    group: root
    mode: 0644
