---
##########################
# packages

kubectl_package_name: kubectl

##########################
# repository

kubectl_configure_repository: true

kubectl_debian_repository_arch: amd64
kubectl_debian_repository_key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
kubectl_debian_repository: "deb [ arch={{ kubectl_debian_repository_arch }} ] https://apt.kubernetes.io/ kubernetes-xenial main"
