---
- name: Wait for apt lock
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done

- name: Install microcode packages
  become: true
  apt:
    name: "{{ microcode_packages }}"
    state: present
