---
- name: Deprecation notice
  fail:
    msg: |
      The use of Zabbix is deprecated and will no longer be supported in the future.
      Please set the ignore_deprecations parameter to True to continue using Zabbix.
  when: not ignore_deprecations|default(False)|bool

- name: Create cluster host
  local_action:
    module: community.zabbix.zabbix_host
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_username }}"
    login_password: "{{ zabbix_login_password }}"
    state: present
    host_name: "{{ zabbix_cluster_name}}"
    visible_name: "{{ zabbix_cluster_name }}"
    host_groups: "{{ zabbix_cluster_host_groups }}"
    status: "{{ zabbix_cluster_status }}"
    interfaces: "{{ zabbix_cluster_interfaces }}"
    link_templates: "{{ zabbix_cluster_link_templates }}"
