---
- name: Wait for apt lock
  become: true
  shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend

- name: Install required packages
  become: true
  apt:
    name: "{{ network_netplan_required_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 86400

- name: Remove ifupdown package
  become: true
  apt:
    name: ifupdown
    state: absent

- name: Create required directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ network_netplan_path }}"

- name: Copy netplan configuration
  become: true
  template:
    src: netplan/01-osism.yaml.j2
    dest: "{{ network_netplan_path }}/01-osism.yaml"
    mode: 0644
    owner: root
    group: root
  notify:
    - Netplan configuration changed

- name: Copy interfaces file
  become: true
  template:
    src: netplan/interfaces.j2
    dest: "{{ network_interfaces_path }}"
    mode: 0644
    owner: root
    group: root

- name: Copy dispatcher scripts
  become: true
  template:
    src: "{{ item.src }}"
    dest: "/etc/networkd-dispatcher/{{ item.dest }}"
    mode: 0755
    owner: root
    group: root
  loop: "{{ network_dispatcher_scripts }}"
