---
zabbix_agent_port: 10050

zabbix_server_host: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
zabbix_server_port: 8160
zabbix_server_url: "http://{{ zabbix_server_host }}:{{ zabbix_server_port }}"

zabbix_login_username: Admin
zabbix_login_password: zabbix

zabbix_host_interfaces_default:
  - type: "1"
    main: "1"
    dns: "{{ inventory_hostname }}"
    port: "{{ zabbix_agent_port }}"
zabbix_host_interfaces_extra: []
zabbix_host_interfaces: "{{ zabbix_host_interfaces_default + zabbix_host_interfaces_extra }}"

zabbix_host_host_groups_default:
  - Linux servers
zabbix_host_host_groups_extra:
zabbix_host_host_groups: "{{ zabbix_host_host_groups_default + zabbix_host_host_groups_extra }}"

zabbix_host_link_templates_default:
  - Linux by Zabbix agent
zabbix_host_link_templates_extra: []
zabbix_host_link_templates: "{{ zabbix_host_link_templates_default + zabbix_host_link_templates_extra }}"

zabbix_host_host_name: "{{ inventory_hostname }}"
zabbix_host_inventory_mode: "automatic"
zabbix_host_status: "enabled"
zabbix_host_visible_name: "{{ inventory_hostname_short }}"
