---
zabbix_server_host: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
zabbix_server_port: 8160
zabbix_server_url: "http://{{ zabbix_server_host }}:{{ zabbix_server_port }}"

zabbix_login_username: Admin
zabbix_login_password: zabbix
