---
##########################
# resolvconf

resolvconf_nameserver_default:
  - 9.9.9.9
  - 149.112.112.112
resolvconf_nameserver_extra: []
resolvconf_nameserver: "{{ resolvconf_nameserver_default + resolvconf_nameserver_extra }}"

resolvconf_fallback_nameserver: []
resolvconf_search: osism.test

resolvconf_minimum_number_of_nameservers: 2

resolvconf_always_validate_dnssec: allow-downgrade
resolvconf_cache: true
resolvconf_dns_over_tls: false
resolvconf_file: /etc/resolv.conf
