---
zabbix_export:
  version: '5.2'
  date: '2021-01-08T14:57:27Z'
  groups:
    -
      name: Templates
  templates:
    -
      template: 'OpenStack Glance'
      name: 'OpenStack Glance'
      groups:
        -
          name: Templates
      applications:
        -
          name: 'OpenStack Glance'
      items:
        -
          name: 'glance: service on port 9292/tcp'
          key: 'net.tcp.service[http,{$OSISM_API_INTERFACE_ADDRESS},9292]'
          delay: '30'
          applications:
            -
              name: 'OpenStack Glance'
          triggers:
            -
              expression: '{last(0)}=0'
              name: 'glance: service is not listening on port 9292 on host {HOST.NAME}'
              priority: HIGH
        -
          name: 'glance: process glance-api'
          key: 'proc.num[python,,,glance-api]'
          delay: '30'
          applications:
            -
              name: 'OpenStack Glance'
          triggers:
            -
              expression: '{last(0)}=0'
              name: 'glance: process glance-api is not running on {HOST.NAME}'
              priority: HIGH
