---
zabbix_export:
  version: '5.2'
  date: '2021-01-08T16:20:05Z'
  groups:
    -
      name: Templates
  templates:
    -
      template: 'OSISM - OpenStack - Horizon'
      name: 'OSISM - OpenStack - Horizon'
      groups:
        -
          name: Templates
      applications:
        -
          name: 'OpenStack - Horizon'
      items:
        -
          name: 'Horizon: Service on port 80/tcp'
          key: 'net.tcp.service[http,{$OSISM_API_INTERFACE_ADDRESS},80]'
          delay: '30'
          applications:
            -
              name: 'OpenStack - Horizon'
          triggers:
            -
              expression: '{last(0)}=0'
              name: 'Horizon: Service is not listening on port 80 on {HOST.NAME}'
              priority: HIGH
        -
          name: 'Horizon: Process wsgi:horizon-http'
          key: 'proc.num[,,,.*wsgi:horizon-htt]'
          delay: '30'
          applications:
            -
              name: 'OpenStack - Horizon'
          triggers:
            -
              expression: '{last(0)}=0'
              name: 'Horizon: Process wsgi:horizon-http is not running on {HOST.NAME}'
              priority: HIGH
