---
##########################
# packages

trivy_package_name: trivy

##########################
# repository

trivy_configure_repository: no

trivy_debian_repository_arch: amd64
trivy_debian_repository_key: https://aquasecurity.github.io/trivy-repo/deb/public.key
trivy_debian_repository: "deb [ arch={{ trivy_debian_repository_arch }} ] https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main"
