---
- name: Remove docker-compose apt preferences file
  become: true
  file:
    path: /etc/apt/preferences.d/docker-compose
    state: absent
  when: not docker_compose_configure_repository|bool

- name: Use docker-compose from backport repository
  become: true
  copy:
    content: |
      Package: {{ docker_compose_package_name }}
      Pin: release o=pbuilder
      Pin-Priority: 999

      Package: python3-requests
      Pin: release o=pbuilder
      Pin-Priority: 999
    dest: /etc/apt/preferences.d/docker-compose
    mode: 0644
  when: docker_compose_configure_repository|bool

- name: Add repository
  become: true
  apt_repository:
    repo: "{{ docker_compose_debian_repository }}"
    state: present
    filename: docker-compose
    update_cache: true
    mode: 0644
  when: docker_compose_configure_repository|bool

- name: Remove docker-compose binary
  become: true
  file:
    path: /usr/local/bin/docker-compose
    state: absent

- name: Wait for apt lock
  become: true
  shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend

- name: Install docker-compose package
  become: true
  apt:
    name: "{{ docker_compose_package_name }}"
    state: present
    install_recommends: false
