---
##########################
# generic

operator_user: dragon
operator_group: "{{ operator_user }}"

##########################
# possible values: git

configuration_type: git

##########################
# directories

configuration_directory: /opt/configuration

##########################
# parameters for configuration type "git"

configuration_git_public_key: ""
configuration_git_private_key: ""
configuration_git_private_key_file: ~/.ssh/id_rsa.configuration
configuration_git_version: master
configuration_git_username: git
configuration_git_host: github.com
configuration_git_port: 22
configuration_git_repository: osism/ansible-configuration.git
configuration_git_protocol: ssh
