---
zabbix_server_host: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
zabbix_server_port: 8160
zabbix_server_url: "http://{{ zabbix_server_host }}:{{ zabbix_server_port }}"

zabbix_login_username: Admin
zabbix_login_password: zabbix

zabbix_cluster_name: ""
zabbix_cluster_status: "enabled"

zabbix_cluster_interfaces_default:
  - type: "1"
    main: "1"
    useip: "1"
    ip: "{{ kolla_internal_vip_address | default('127.0.0.1') }}"
    port: 0
zabbix_cluster_interfaces_extra: []
zabbix_cluster_interfaces: "{{ zabbix_cluster_interfaces_default + zabbix_cluster_interfaces_extra }}"

zabbix_cluster_link_templates_default: []
zabbix_cluster_link_templates_extra: []
zabbix_cluster_link_templates: "{{ zabbix_cluster_link_templates_default + zabbix_cluster_link_templates_extra }}"

zabbix_cluster_host_groups_default:
  - Cluster
zabbix_cluster_host_groups_extra: []
zabbix_cluster_host_groups: "{{ zabbix_cluster_host_groups_default + zabbix_cluster_host_groups_extra }}"
