---
- name: Create custom facts directory
  become: true
  file:
    path: /etc/ansible/facts.d
    state: "directory"
    owner: root
    group: root
    mode: 0755

- name: Copy fact files
  become: true
  copy:
    src: "{{ item }}.fact"
    dest: "/etc/ansible/facts.d/{{ item }}.fact"
    owner: root
    group: root
    mode: 0755
  loop: "{{ fact_files }}"
