---
- name: Enable kernel modules
  become: true
  lineinfile:
    line: "{{ item }}"
    dest: /etc/modules
    mode: 0644
    state: present
  loop: "{{ kernel_modules }}"

- name: Load kernel module
  become: true
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kernel_modules }}"
