---
- name: Collect facts about services
  scan_services:

- name: Check services
  debug:
    msg: "The {{ item }} service is running. It should be deactivated and not run."
  loop: "{{ services_warning }}"
  when: item + ".service" in services

- name: Start/enable required services
  become: true
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  ignore_errors: true
  loop: "{{ services_required }}"
  when: item + ".service" in services
