---
name: Test role state

"on":
  push:
    paths:
      - '.github/workflows/test-role-state.yml'
      - 'molecule/default/*'
      - 'molecule/state/**'
      - 'roles/state/**'
  pull_request:
    paths:
      - '.github/workflows/test-role-state.yml'
      - 'molecule/default/*'
      - 'molecule/state/**'
      - 'roles/state/**'

jobs:
  test-role-state:

    runs-on: ubuntu-latest

    env:
      MOLECULE_ROLE: state

    strategy:
      max-parallel: 4
      matrix:
        ansible-version: [3.2.0]
        python-version: [3.6, 3.8]
        docker-image: ['ubuntu:20.04']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install dependencies
        run: |
          python3 -m pip install --use-feature=2020-resolver --upgrade pip
          python3 -m pip install --use-feature=2020-resolver -r molecule/requirements.txt
          python3 -m pip install --use-feature=2020-resolver ansible~=${{ matrix.ansible-version }}
      - name: Run molecule
        run: molecule test
        env:
          MOLECULE_DOCKER_IMAGE: "${{ matrix.docker-image }}"
      - name: Cleanup molecule
        run: molecule destroy
        env:
          MOLECULE_DOCKER_IMAGE: "${{ matrix.docker-image }}"
        if: ${{ always() }}
