---
- name: Set link_templates fact
  set_fact:
    link_templates: "{{ zabbix_host_link_templates }}"

- name: Add 'Docker' template
  set_fact:
    link_templates: "{{ link_templates + ['Docker'] }}"
  when: "'docker' in group_names"

- name: Add 'OpenStack Glance' template
  set_fact:
    link_templates: "{{ link_templates + ['OpenStack Glance'] }}"
  when: "'glance-api' in group_names"

- name: Add 'OpenStack Horizon' template
  set_fact:
    link_templates: "{{ link_templates + ['OpenStack Horizon'] }}"
  when: "'horizon' in group_names"

- name: Add 'OpenStack Keystone' template
  set_fact:
    link_templates: "{{ link_templates + ['OpenStack Keystone'] }}"
  when: "'keystone' in group_names"

- name: Create host
  local_action:
    module: community.zabbix.zabbix_host
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_username }}"
    login_password: "{{ zabbix_login_password }}"
    state: present
    host_name: "{{ zabbix_host_host_name }}"
    visible_name: "{{ zabbix_host_visible_name }}"
    host_groups: "{{ zabbix_host_host_groups }}"
    status: "{{ zabbix_host_status }}"
    inventory_mode: "{{ zabbix_host_inventory_mode }}"
    inventory_zabbix: "{{ zabbix_host_inventory }}"
    interfaces: "{{ zabbix_host_interfaces }}"
    link_templates: "{{ link_templates }}"

- name: Create OSISM_API_INTERFACE_ADDRESS macro
  local_action:
    module: community.zabbix.zabbix_hostmacro
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_username }}"
    login_password: "{{ zabbix_login_password }}"
    state: present
    host_name: "{{ zabbix_host_host_name }}"
    macro_name: "{$OSISM_API_INTERFACE_ADDRESS}"
    macro_value: "{{ 'api' | kolla_address }}"
